Lecture1/Models/Calculator.cs
namespace Lecture1.Models;

public class Calculator
{
    private static Dictionary<Operators, Func<double, double, double>> _calc = new()
    {
        { Operators.Add, (a, b) => a + b },
        { Operators.Sub, (a, b) => a - b },
        { Operators.Mul, (a, b) => a * b },
        { Operators.Div, (a, b) => a / b },
    };
    public static double Calculate(CalculatorViewModel model)
    {
        return _calc[model.Operator](model.X , model.Y);
    }
}

Lecture1/Models/CalculatorModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace Lecture1.Models;

public class CalculatorModel
{
    [Required]
    public double? X { get; set; }
    
    [Required]
    public double? Y { get; set; }
    
    [Required]
    public Operators? Operator { get; set; }
}

Lecture1/Models/CalculatorViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Lecture1.Models;

public class CalculatorViewModel
{
    private static Dictionary<Operators, string> _symbols = new()
        {
            { Operators.Add, "+"},
            { Operators.Sub, "−"},
            { Operators.Mul, "×"},
            { Operators.Div, "÷"}
        };
    [Required]
    public double X { get; init; }
    [Required]
    public double Y { get; init; }
    [Required(ErrorMessage = "Nie wybrano operatora")]
    public Operators Operator { get; set; }
    public double? Result { get; set; }
    
    public List<SelectListItem> OperatorEntities => _symbols.Select(item => new SelectListItem()
    {
        Value = item.Key.ToString(),
        Text = item.Value
    }).ToList();
    
    public string View => Result is not null ? $"{X} {_symbols[Operator]} {Y} = {Result}" : "Błąd obliczeń";
    
    public static CalculatorViewModel WithoutResult(CalculatorModel model)
    {
        return new CalculatorViewModel()
        {
            X = model.X??0,
            Y = model.Y??0,
            Result = null,
            Operator = model.Operator??Operators.Add
        };
    }
    
    public static CalculatorViewModel WithResult(CalculatorModel model, double result)
    {
        return new CalculatorViewModel()
        {
            X = model.X??0,
            Y = model.Y??0,
            Result = result,
            Operator = model.Operator??Operators.Add
        };
    }
}

Lecture1/Models/ErrorViewModel.cs
namespace Lecture1.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Lecture1/Models/Operators.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Lecture1.Models;

public enum Operators
{
    [Display(Name = "+")]
    Add, 
    [Display(Name = "−")]
    Sub, 
    [Display(Name = "×")]
    Mul, 
    [Display(Name = "÷")]   
    Div
}

Lecture1/Controllers/CalculatorController.cs
using Lecture1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lecture1.Controllers;

public class CalculatorController(ILogger<CalculatorController> logger): Controller
{
    public IActionResult Index()
    {
        return View(new CalculatorModel());       
    }
    [HttpGet]
    public IActionResult Result(CalculatorViewModel model)
    {
        logger.LogInformation("Obliczanie: {X} {Op} {Y}", model.X, model.Operator, model.Y);
        if (!ModelState.IsValid)
        {
            model.Result = null;
            return View(model);
        }
        model.Result = Calculator.Calculate(model);
        return View(model);       
    }
}

Lecture1/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Lecture1.Models;

namespace Lecture1.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Lecture1/Controllers/RequestController.cs
using Microsoft.AspNetCore.Mvc;

namespace Lecture1.Controllers;

public class RequestController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }

    public string Info()
    {
        string[] arr =
        [
            Request.Path.ToString(),
            Request.QueryString.ToString(),
            Request.Method,
            Request.Host.ToString(),
            Request.Scheme,
            Request.ContentType??"brak",
            Request.Headers["User-Agent"],
        ];
        return string.Join(", ", arr);
    }
}

Lecture1/Views/Request/Index.cshtml
@using System.Reflection.Metadata.Ecma335
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<h2>Szczegóły żądania</h2>
<p>Strona (plik <code>Views/Request/Index.cshtml</code>) wyświetla podstawowe informacje zawarte w żądaniu, posługująć się kontekstem (<code>Context</code>)</p>
<p>Jednocześnie strona ta jest przykładem łamania wzorca MVC, gdyż plik cshtml pełni rolę widoku, modelu i kontrolera.</p>
<p>Składowa <code>Request</code> kontekstu to żądanie</p>
<p>Składowa <code>Response</code> kontekstu to odpowiedź</p>
@* <p>&lt; &times; &divide; &minus; &plus;</p> *@
<p>Widok oczekuje żądania z parametrami: a, b i  op</p>
<p>Dodaj w pasku adresu na końcu url query <code>?a=3&b=4&op=add</code></p>
<h3>Szczegóły żądania</h3>
@foreach (var key in Context.Request.Query.Keys)
{
    <p>@key: @Context.Request.Query[key]</p>
}
<p>Metoda żądanie: @Context.Request.Method</p>
<p>Ścieżka żądania: @Context.Request.Path</p>
<p>Quey żądania: @Context.Request.QueryString</p>
@{
    if (!Context.Request.Query.ContainsKey("op"))
    {
        return;
    }
    
    var op = Context.Request.Query["op"];
    try
    {
        double a = double.Parse(@Context.Request.Query["a"]);
        double b = double.Parse(@Context.Request.Query["b"]);
        Func<double, double, double> add = (a, b) => a + b;
        Dictionary<string, Func<double, double, double>> calc = new()
        {
            { "add", (a, b) => a + b },
            { "sub", (a, b) => a - b },
            { "mul", (a, b) => a * b },
            { "div", (a, b) => a / b },
        };
        Dictionary<string, string> symbols = new()
        {
            {"add", "&plus;"},
            {"sub", "&minus;"},
            {"mul", "&times;"},
            {"div", "&divide;"}
            
        };
        if (!calc.ContainsKey(op))
        {
            Context.Response.StatusCode = 400;
            <h3 class="text-danger">Niepoprawny operator!</h3>
        }
        else
        {
            var result = calc[op](a, b);
            <h1>Kalkulator</h1>
            <h2>
                @a @Html.Raw(@symbols[op]) @b = @result
            </h2>
        }
    }
    catch (FormatException e)
    {
        Context.Response.StatusCode = 400;
        <p>Niepoprawny format liczby!</p>
    }
}

Lecture1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Lecture1</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Lecture1.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <img src="https://wsei.edu.pl/wp-content/uploads/2019/03/wsei-logo-svg.svg" width="180" alt="wsei logo"/></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Index">Request</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Index">Calculator</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - Lecture1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>